# Generated by Django 6.0.4 on 2026-09-27 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cross',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('category', models.CharField(choices=[('Community Hall', 'Community Hall'), ('Sports Cross Arena', 'Sports Cross Arena'), ('Event & Celebration', 'Event & Celebration'), ('Conference & Workshop', 'Conference & Workshop'), ('Fitness / Crossfit Space', 'Fitness / Crossfit Space'), ('Creative Studio Cross', 'Creative Studio Cross')], default='Community Hall', max_length=50)),
                ('description', models.TextField(help_text='Detailed overview of the cross property')),
                ('location', models.CharField(help_text='City or Neighborhood (e.g. Metro Center, Downtown)', max_length=100)),
                ('address', models.TextField(help_text='Full physical street address')),
                ('price', models.DecimalField(decimal_places=2, help_text='Hourly rental price (USD / INR)', max_digits=10)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum capacity of people allowed')),
                ('image', models.ImageField(blank=True, help_text='Upload local photo', null=True, upload_to='crosses/')),
                ('image_url', models.URLField(blank=True, help_text='Or provide direct web image URL', max_length=600, null=True)),
                ('facilities', models.TextField(help_text='Comma-separated amenities (e.g. Wi-Fi, Air Conditioning, Projector, Sound System, Restrooms, Parking)')),
                ('rules', models.TextField(default='No smoking inside. Clean up after use. Adhere to agreed time limits.', help_text='House rules and policies')),
                ('cancellation_policy', models.TextField(default='Free cancellation up to 24 hours prior to booking start time.', help_text='Terms for booking cancellation')),
                ('is_active', models.BooleanField(default=True, help_text='Property active status for bookings')),
                ('is_approved', models.BooleanField(default=True, help_text='Admin approval status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crosses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cross Property',
                'verbose_name_plural': 'Cross Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrossReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, '5 - Exceptional'), (4, '4 - Very Good'), (3, '3 - Average'), (2, '2 - Poor'), (1, '1 - Terrible')], default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('cross', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='crosses.cross')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
