# Generated by Django 6.0.4 on 2026-09-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cross',
            name='decks_count',
            field=models.PositiveIntegerField(default=16, help_text='Total passenger decks'),
        ),
        migrations.AddField(
            model_name='cross',
            name='departure_port',
            field=models.CharField(default='Port of Miami, Florida', help_text='Embarkation terminal', max_length=120),
        ),
        migrations.AddField(
            model_name='cross',
            name='destination',
            field=models.CharField(default='Caribbean Seas', help_text='Primary voyage destination', max_length=150),
        ),
        migrations.AddField(
            model_name='cross',
            name='dining_venues',
            field=models.TextField(blank=True, default="The Captain's Table, Oceanview Lido Buffet, Starlight Lounge, Sunset Seafood Grill"),
        ),
        migrations.AddField(
            model_name='cross',
            name='duration_days',
            field=models.PositiveIntegerField(default=5, help_text='Standard cruise duration in days'),
        ),
        migrations.AddField(
            model_name='cross',
            name='entertainment',
            field=models.TextField(blank=True, default='Grand Theatre Broadway Show, Casino Royale, Infinity Sunset Pool, Jazz Club, Spa Wellness'),
        ),
        migrations.AddField(
            model_name='cross',
            name='itinerary_highlights',
            field=models.TextField(blank=True, default="Day 1: Embarkation & Captain's Welcome Dinner\nDay 2: Ocean Navigation & Sun Deck Gala\nDay 3: Tropical Island Snorkeling Excursion\nDay 4: Starlight Pool Party & Broadway Theatre\nDay 5: Return to Home Port & Disembarkation"),
        ),
        migrations.AddField(
            model_name='cross',
            name='route',
            field=models.CharField(default='Miami - Bahamas - Cozumel - Miami', help_text='Cruise route / ports sequence', max_length=250),
        ),
        migrations.AddField(
            model_name='cross',
            name='ship_length_meters',
            field=models.PositiveIntegerField(default=330, help_text='Vessel length in meters'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='address',
            field=models.TextField(help_text='Full physical terminal / dock street address'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='cancellation_policy',
            field=models.TextField(default='Full refund up to 48 hours prior to scheduled departure. Flexible date rescheduling available.', help_text='Terms for booking cancellation'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Maximum passenger capacity'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='category',
            field=models.CharField(choices=[('Luxury Ocean Cruise', 'Luxury Ocean Cruise'), ('Mega Cruise Liner', 'Mega Cruise Liner'), ('Expedition Cruise', 'Expedition Cruise'), ('Island Hopper Cruise', 'Island Hopper Cruise'), ('Scenic Coastal Cruise', 'Scenic Coastal Cruise'), ('Private Charter Yacht', 'Private Charter Yacht'), ('Community Hall', 'Community Hall'), ('Sports Cross Arena', 'Sports Cross Arena'), ('Event & Celebration', 'Event & Celebration'), ('Conference & Workshop', 'Conference & Workshop'), ('Fitness / Crossfit Space', 'Fitness / Crossfit Space'), ('Creative Studio Cross', 'Creative Studio Cross')], default='Luxury Ocean Cruise', max_length=50),
        ),
        migrations.AlterField(
            model_name='cross',
            name='description',
            field=models.TextField(help_text='Detailed overview of the cross property or cruise vessel'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='facilities',
            field=models.TextField(help_text='Comma-separated amenities (e.g. Wi-Fi, Air Conditioning, Swimming Pool, Heliport, Fitness Center, Dining)'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='location',
            field=models.CharField(help_text='Home Port / Region (e.g. Port of Miami, Barcelona, Nassau)', max_length=100),
        ),
        migrations.AlterField(
            model_name='cross',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Starting ticket fare / hourly private charter rate', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cross',
            name='rules',
            field=models.TextField(default='Valid passport required. Safety lifeboat drill mandatory on embarkation. Quiet hours after 11 PM.', help_text='Voyage rules and policies'),
        ),
    ]
