# Generated by Django 6.0.4 on 2026-09-28 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosses', '0002_cross_decks_count_cross_departure_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount (%)'), ('FIXED', 'Fixed Amount (₹)')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_booking_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cross',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cruise Ship', 'verbose_name_plural': 'Cruise Ships'},
        ),
        migrations.AddField(
            model_name='cross',
            name='beam_meters',
            field=models.PositiveIntegerField(default=34, help_text='Vessel beam width in meters'),
        ),
        migrations.AddField(
            model_name='cross',
            name='cabin_count',
            field=models.PositiveIntegerField(default=180, help_text='Total staterooms and suites'),
        ),
        migrations.AddField(
            model_name='cross',
            name='supports_birthdays',
            field=models.BooleanField(default=True, help_text='Supports birthday parties and milestones'),
        ),
        migrations.AddField(
            model_name='cross',
            name='supports_conferences',
            field=models.BooleanField(default=True, help_text='Equipped with conference AV and theatre halls'),
        ),
        migrations.AddField(
            model_name='cross',
            name='supports_corporate',
            field=models.BooleanField(default=True, help_text='Supports corporate retreats and conferences'),
        ),
        migrations.AddField(
            model_name='cross',
            name='supports_dinners',
            field=models.BooleanField(default=True, help_text='Supports private chef gala dining'),
        ),
        migrations.AddField(
            model_name='cross',
            name='supports_parties',
            field=models.BooleanField(default=True, help_text='Supports DJ decks, cocktail soirees and dance floors'),
        ),
        migrations.AddField(
            model_name='cross',
            name='supports_private_charter',
            field=models.BooleanField(default=True, help_text='Available for full private hire/charter'),
        ),
        migrations.AddField(
            model_name='cross',
            name='supports_public_tours',
            field=models.BooleanField(default=True, help_text='Offers ticketed public cruise departures'),
        ),
        migrations.AddField(
            model_name='cross',
            name='supports_weddings',
            field=models.BooleanField(default=True, help_text='Supports ocean wedding ceremonies and receptions'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='address',
            field=models.TextField(help_text='Full passenger embarkation terminal address'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='cancellation_policy',
            field=models.TextField(default='Full refund up to 72 hours prior to scheduled departure. Flexible date rescheduling available.', help_text='Terms for booking cancellation'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Maximum passenger / guest capacity'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='category',
            field=models.CharField(choices=[('Luxury Ocean Cruise', 'Luxury Ocean Cruise'), ('Mega Cruise Liner', 'Mega Cruise Liner'), ('Expedition Cruise Vessel', 'Expedition Cruise Vessel'), ('Island Hopper Cruise', 'Island Hopper Cruise'), ('Scenic Coastal Cruise', 'Scenic Coastal Cruise'), ('Private Charter Yacht', 'Private Charter Yacht'), ('Luxury Catamaran Cruiser', 'Luxury Catamaran Cruiser')], default='Luxury Ocean Cruise', max_length=50),
        ),
        migrations.AlterField(
            model_name='cross',
            name='decks_count',
            field=models.PositiveIntegerField(default=12, help_text='Total passenger decks'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='departure_port',
            field=models.CharField(default='Mumbai International Cruise Terminal', help_text='Embarkation terminal', max_length=120),
        ),
        migrations.AlterField(
            model_name='cross',
            name='description',
            field=models.TextField(help_text='Detailed overview of the cruise ship or luxury vessel'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='destination',
            field=models.CharField(default='Goa & Arabian Sea', help_text='Primary voyage destination', max_length=150),
        ),
        migrations.AlterField(
            model_name='cross',
            name='dining_venues',
            field=models.TextField(blank=True, default="The Captain's Table, Oceanview Lido Buffet, Starlight Lounge, Coastal Seafood Grill, Spice Panorama"),
        ),
        migrations.AlterField(
            model_name='cross',
            name='duration_days',
            field=models.PositiveIntegerField(default=4, help_text='Standard voyage duration in days'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='entertainment',
            field=models.TextField(blank=True, default='Grand Oceanfront Broadway Show, Casino Royale, Infinity Sunset Pool, Starlight Jazz Club, Ayurvedic Spa'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='facilities',
            field=models.TextField(help_text='Comma-separated amenities (e.g. Wi-Fi, Swimming Pool, Heliport, Fine Dining, DJ Audio Rigs, Theatre, Spa)'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or direct web image URL', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='cross',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Ship active status for bookings'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='itinerary_highlights',
            field=models.TextField(blank=True, default='Day 1: Embarkation & Welcome Gala Dinner\nDay 2: Coastal Navigation & Sun Deck Cabana Soiree\nDay 3: Scenic Island Anchorage & Water Sports\nDay 4: Starlight Farewell Party & Return to Port'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='location',
            field=models.CharField(help_text='Home Port / Base Location (e.g. Mumbai, Goa, Kochi, Chennai, Port Blair)', max_length=100),
        ),
        migrations.AlterField(
            model_name='cross',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Starting base rate in INR (₹)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cross',
            name='route',
            field=models.CharField(default='Mumbai - Goa - Lakshadweep - Mumbai', help_text='Cruise route / ports sequence', max_length=250),
        ),
        migrations.AlterField(
            model_name='cross',
            name='rules',
            field=models.TextField(default='Valid government photo ID required. Mandatory safety lifeboat briefing prior to departure. Quiet hours observed after midnight.', help_text='Voyage rules and policies'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='ship_length_meters',
            field=models.PositiveIntegerField(default=280, help_text='Vessel length in meters'),
        ),
        migrations.CreateModel(
            name='PublicTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('departure_port', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('return_date', models.DateField()),
                ('return_time', models.TimeField()),
                ('duration_days', models.PositiveIntegerField(default=3)),
                ('total_capacity', models.PositiveIntegerField(help_text='Total ticket capacity for this voyage')),
                ('booked_capacity', models.PositiveIntegerField(default=0)),
                ('adult_price', models.DecimalField(decimal_places=2, help_text='Fare per adult in INR (₹)', max_digits=10)),
                ('child_price', models.DecimalField(decimal_places=2, help_text='Fare per child in INR (₹)', max_digits=10)),
                ('itinerary', models.TextField(blank=True, default='')),
                ('ports_of_call', models.CharField(blank=True, default='', max_length=255)),
                ('meals_included', models.CharField(default='All Gourmet Meals & High Tea Included', max_length=200)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('BOARDING', 'Boarding Now'), ('DEPARTED', 'Departed / In Transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_tours', to='crosses.cross')),
            ],
            options={
                'ordering': ['departure_date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='ShipExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in INR (₹)', max_digits=10)),
                ('pricing_mode', models.CharField(choices=[('FIXED', 'Fixed Flat Fee'), ('PER_GUEST', 'Per Guest Fee')], default='FIXED', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='crosses.cross')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
