# Generated by Django 6.0.4 on 2026-09-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('booking_date', models.DateField(help_text='Target date of booking')),
                ('start_time', models.TimeField(help_text='Start time of slot')),
                ('end_time', models.TimeField(help_text='End time of slot')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Hourly base price at booking time', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Calculated total price on server', max_digits=10)),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
