# Generated by Django 6.0.4 on 2026-09-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('TOUR', 'Cruise Tour & Travel Ticket'), ('EVENT', 'Private Maritime Event')], default='TOUR', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='cabin_type',
            field=models.CharField(blank=True, default='Royal Balcony Stateroom', max_length=80),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_package',
            field=models.CharField(blank=True, help_text='Sapphire Anchor, Emerald Wave, Diamond Horizon', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_type',
            field=models.CharField(blank=True, help_text='Wedding, Birthday, Corporate, Gala Dinner, Conference', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_code_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
