# Generated by Django 6.0.4 on 2026-09-28 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_booking_type_booking_cabin_type_and_more'),
        ('crosses', '0003_offer_alter_cross_options_cross_beam_meters_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='children_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='extras_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='promo_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='public_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='crosses.publictour'),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_extras',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='tracking_status',
            field=models.CharField(choices=[('BOOKED', 'Reservation Placed'), ('CONFIRMED', 'Booking Confirmed'), ('BOARDING', 'Boarding Now'), ('DEPARTED', 'Departed / In Transit'), ('ARRIVED', 'Arrived at Destination'), ('COMPLETED', 'Voyage Completed'), ('CANCELLED', 'Reservation Cancelled')], default='BOOKED', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Base rate at booking time', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(help_text='Target date of booking or tour embarkation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('TOUR', 'Public Cruise Tour Ticket'), ('EVENT', 'Private Ship Charter / Event')], default='TOUR', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(help_text='End time of slot or disembarkation time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1, help_text='Total passenger headcount'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(help_text='Start time of slot or embarkation time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Final server-calculated amount in INR (₹)', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['public_tour', 'status'], name='bookings_bo_public__e3720e_idx'),
        ),
    ]
